Add missing includes
drmmode_display.c: In function 'drmmode_handle_uevents':
drmmode_display.c:1953:14: error: storage size of 's' isn't known
  struct stat s;
              ^
drmmode_display.c:1966:2: error: implicit declaration of function 'fstat' [-Werror=implicit-function-declaration]
  if (fstat(pARMSOC->drmFD, &s)) {